//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for RepositoryForgeType.
const (
	Forgejo     RepositoryForgeType = "forgejo"
	Github      RepositoryForgeType = "github"
	LessThannil RepositoryForgeType = "<nil>"
)

// Valid indicates whether the value is a known member of the RepositoryForgeType enum.
func (e RepositoryForgeType) Valid() bool {
	switch e {
	case Forgejo:
		return true
	case Github:
		return true
	case LessThannil:
		return true
	default:
		return false
	}
}

// Commit defines model for Commit.
type Commit struct {
	Author string             `json:"author"`
	Date   openapi_types.Date `json:"date"`

	// Message First line of the commit message.
	Message string `json:"message"`
	Sha     string `json:"sha"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Report defines model for Report.
type Report struct {
	// AuthorCounts Map of author name to commit count.
	AuthorCounts *map[string]int `json:"author_counts,omitempty"`
	Authors      *[]string       `json:"authors,omitempty"`
	CommitCount  int             `json:"commit_count"`
	Commits      *[]Commit       `json:"commits,omitempty"`
	CreatedAt    time.Time       `json:"created_at"`
	Id           int64           `json:"id"`
	RepoId       int64           `json:"repo_id"`

	// Summary AI-generated narrative summary of activity in this week.
	Summary   *string            `json:"summary,omitempty"`
	UpdatedAt time.Time          `json:"updated_at"`
	Week      int                `json:"week"`
	WeekEnd   openapi_types.Date `json:"week_end"`
	WeekStart openapi_types.Date `json:"week_start"`
	Year      int                `json:"year"`
}

// ReportSummary defines model for ReportSummary.
type ReportSummary struct {
	CommitCount int       `json:"commit_count"`
	CreatedAt   time.Time `json:"created_at"`
	Id          int64     `json:"id"`
	RepoId      int64     `json:"repo_id"`

	// Week ISO week number.
	Week      int                `json:"week"`
	WeekEnd   openapi_types.Date `json:"week_end"`
	WeekStart openapi_types.Date `json:"week_start"`
	Year      int                `json:"year"`
}

// Repository defines model for Repository.
type Repository struct {
	Active    bool      `json:"active"`
	Branch    string    `json:"branch"`
	CreatedAt time.Time `json:"created_at"`

	// Description AI-generated description from the project README.
	Description *string `json:"description,omitempty"`

	// External External repo - contributor analysis is included in summaries.
	External   bool                 `json:"external"`
	ForgeOwner *string              `json:"forge_owner,omitempty"`
	ForgeRepo  *string              `json:"forge_repo,omitempty"`
	ForgeType  *RepositoryForgeType `json:"forge_type,omitempty"`
	Id         int64                `json:"id"`
	LastRunAt  *time.Time           `json:"last_run_at,omitempty"`
	Name       string               `json:"name"`
	Private    bool                 `json:"private"`
	UpdatedAt  time.Time            `json:"updated_at"`
	Url        string               `json:"url"`
}

// RepositoryForgeType defines model for Repository.ForgeType.
type RepositoryForgeType string

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListReposParams defines parameters for ListRepos.
type ListReposParams struct {
	// Active If set, only return repositories with this active state.
	Active *bool `form:"active,omitempty" json:"active,omitempty"`
}

// ListReportsForRepoParams defines parameters for ListReportsForRepo.
type ListReportsForRepoParams struct {
	// Year If set, only return reports for the given ISO year.
	Year *int `form:"year,omitempty" json:"year,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Fetch a weekly report by ID
	// (GET /reports/{id})
	GetReport(w http.ResponseWriter, r *http.Request, id int64)
	// List repositories
	// (GET /repos)
	ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams)
	// List weekly reports for a repository
	// (GET /repos/{name}/reports)
	ListReportsForRepo(w http.ResponseWriter, r *http.Request, name string, params ListReportsForRepoParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetReport operation middleware
func (siw *ServerInterfaceWrapper) GetReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReport(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepos operation middleware
func (siw *ServerInterfaceWrapper) ListRepos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReposParams

	// ------------- Optional query parameter "active" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "active", r.URL.Query(), &params.Active, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "active"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListReportsForRepo operation middleware
func (siw *ServerInterfaceWrapper) ListReportsForRepo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListReportsForRepoParams

	// ------------- Optional query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "year", r.URL.Query(), &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListReportsForRepo(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reports/{id}", wrapper.GetReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos", wrapper.ListRepos)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/repos/{name}/reports", wrapper.ListReportsForRepo)

	return m
}

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetReportRequestObject struct {
	Id int64 `json:"id"`
}

type GetReportResponseObject interface {
	VisitGetReportResponse(w http.ResponseWriter) error
}

type GetReport200JSONResponse Report

func (response GetReport200JSONResponse) VisitGetReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReport401JSONResponse) VisitGetReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReport404JSONResponse struct{ NotFoundJSONResponse }

func (response GetReport404JSONResponse) VisitGetReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListReposRequestObject struct {
	Params ListReposParams
}

type ListReposResponseObject interface {
	VisitListReposResponse(w http.ResponseWriter) error
}

type ListRepos200JSONResponse []Repository

func (response ListRepos200JSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRepos401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListRepos401JSONResponse) VisitListReposResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsForRepoRequestObject struct {
	Name   string `json:"name"`
	Params ListReportsForRepoParams
}

type ListReportsForRepoResponseObject interface {
	VisitListReportsForRepoResponse(w http.ResponseWriter) error
}

type ListReportsForRepo200JSONResponse []ReportSummary

func (response ListReportsForRepo200JSONResponse) VisitListReportsForRepoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsForRepo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListReportsForRepo401JSONResponse) VisitListReportsForRepoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListReportsForRepo404JSONResponse struct{ NotFoundJSONResponse }

func (response ListReportsForRepo404JSONResponse) VisitListReportsForRepoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Fetch a weekly report by ID
	// (GET /reports/{id})
	GetReport(ctx context.Context, request GetReportRequestObject) (GetReportResponseObject, error)
	// List repositories
	// (GET /repos)
	ListRepos(ctx context.Context, request ListReposRequestObject) (ListReposResponseObject, error)
	// List weekly reports for a repository
	// (GET /repos/{name}/reports)
	ListReportsForRepo(ctx context.Context, request ListReportsForRepoRequestObject) (ListReportsForRepoResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetReport operation middleware
func (sh *strictHandler) GetReport(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetReportRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReport(ctx, request.(GetReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReportResponseObject); ok {
		if err := validResponse.VisitGetReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepos operation middleware
func (sh *strictHandler) ListRepos(w http.ResponseWriter, r *http.Request, params ListReposParams) {
	var request ListReposRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepos(ctx, request.(ListReposRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReposResponseObject); ok {
		if err := validResponse.VisitListReposResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListReportsForRepo operation middleware
func (sh *strictHandler) ListReportsForRepo(w http.ResponseWriter, r *http.Request, name string, params ListReportsForRepoParams) {
	var request ListReportsForRepoRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListReportsForRepo(ctx, request.(ListReportsForRepoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListReportsForRepo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListReportsForRepoResponseObject); ok {
		if err := validResponse.VisitListReportsForRepoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FdRb9s2EP4rBLdHxXbWYg9+89ZkMLBuRYo9NUFKS2eLrUSqx5NbLfB/H46kLCmWY7cphmFvtni8+3j3",
	"3fHjg0xtWVkDhpycP0gEV1njwP/5w9K1rU3Gv1NrCAzxT1VVhU4VaWumH5w1/M2lOZSKf/2IsJZz+cO0",
	"czwNq256hWhR7na7RGbgUtQVO5FzeQOfanAEmUBwtsYURGbBCWNJwBftaCJ3ifzLqJpyi/pv+BcwLWrK",
	"wVD0KhA+1RohExYF2Y9ghHZCm60qdDaRvD165IC/2rLUHliFtgIkHTIa8PMvaiqQc+kItdnw4TJFwAtr",
	"i6UiOQ8fkkPDEpxTG287BHyt0ZEotAFh14JyEKmHIeKOyZg3l6sROLtEtueV83feKGnBJy2yFsjd3q1d",
	"fYCU2G3I6sH5of38dLxgNub3BiqLRxN7n9o6Elllmea8qOLNwDB61IZgAygPqv5aVZy94E8YVYIg2ybS",
	"u++lscMV7H0ETVC60RLHDwpRNfw/eA2gx7EFi6Hbp8gceTcWC0ERZPeKDkh2QbocZZrOBrba0M8vO7se",
	"TITK3p9t7eqyVNgcEnixvNiAAWSgwjB00lsQ0d6XJSW91dQIbQTl2onPAB+5IKYuCrUqQM4Jaxg5S11l",
	"X31+dj5eF165B5Od1bDe2JFCOsu8AYVjUR/1iM5kl/i4K0IehOyBfcS4ASkGGTreeW+72g0b8Awu/3cY",
	"2BZ2SL/l2z89n4SpyxXg5OjW/1fljxXbabJjlfY9CD2cK2sLUIb3rVCZNB8dft9S/kF9npwWvSWxRlv6",
	"669CywcSN1eLV6+vzhoT8IUAjSoOw13FFcGZFxeCxQfqVU0WhTKqaBzrAZYEaVFnkPGICpNLg+txqZet",
	"tcUN3NvPBnzZT4IL9hz/K8zD5wcJpi6ZPRtNeb2ScfmDlQk7ujsjN2e3V6Ec3WNtnqr1yWh89Y4SqUK9",
	"jVrpMKXfMuZrLE5LEt9qHlPYsOd60jZEh6xHo6+ZsXw1QlqjpuYt3+eh3VagEJDF6EgLvFlGLVqh3erI",
	"uveLqJK9cJ2LX7wHcVvPZi9Sb+5/wnuRg8rCoPMCwufSG3dpyomqoI61WdtDCDegsgtrikYwmDU3Q5qC",
	"c9psBKFKP3pNH6eJBieUyfyULZruNkd/t7hb0zX0qvEtvGhNHOBWpzARS9b8fFKOlVrj6jK0/aoRi6VQ",
	"GxZEHOXWWMoBWcrZ0vtMC82Lk1vD59PE7JP7CIs3S5nILaALJ7uczCYz5oetwKhKy7l8MZlNXnChFeW+",
	"ONOIfPqgsx1/2ACN5YhqNM4faF0XRTxvHBU+U3zU/jyLmieJQtQlPm8V4MVe05PKFCkuHk9nX+tlJufy",
	"N6CokhkoqhIIWJm+e5Ca0TD4lsvz9jJpiR6asXs5nez23V0yfDT+NJt9t7dZPMfogzGsJPLl7PKYmz2u",
	"6eDl6De9PL1p//zd9UWrvAZKc6FaEsdarhqxfOUtPSfcSTKoohhtkETYKjxcikasdUGAoR3CmBGOFNXu",
	"sOy/a+fr7g7L/kjmrIUDSoRvWvRohh36WVMe1HUvpH89ev58qgGbjkD76deV9PFYfjZHznr79DTLwftn",
	"nEDBWhTafSuTBsTgCgwy2aPD9IHTtWvnxUl2DMm11xF+6PGwYG893jSJKK2PnoIhsdbo6DhFkNy1Rf51",
	"iiu9LPmnsHICYaNdIKV/hIFwjSMo9/wYzpd4ZR6fMAfX7rl8RerSsdFbMIIFPKvhY1SNSvkg9vcbZmcT",
	"tXtJncnVPQuexdfnTT5P8AEzQwVUj4gBf6tjPKX6CubdHeeYL/NxwrGI2F5GjTWX0+2l3N3t/gkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
